export interface MedicalQuestion {
  id: number;
  question: string;
  answer: string;
  category: string;
  difficulty: "easy" | "medium" | "hard";
  explanation: string;
  ambiguityType: "precise" | "ambiguous";
  sourceType: "textbook_fact" | "clinical_guideline" | "constructed";
}

export const medicalDataset: MedicalQuestion[] = [
  {
    id: 1,
    question: "What is the first-line treatment for type 2 diabetes mellitus?",
    answer: "Metformin",
    category: "Pharmacology",
    difficulty: "easy",
    explanation: "Metformin is the preferred initial pharmacologic agent for type 2 diabetes due to its efficacy, safety, and low cost.",
    ambiguityType: "ambiguous",
    sourceType: "clinical_guideline",
  },
  {
    id: 2,
    question: "Which enzyme is deficient in Phenylketonuria (PKU)?",
    answer: "Phenylalanine hydroxylase",
    category: "Biochemistry",
    difficulty: "medium",
    explanation: "PKU is caused by a deficiency of phenylalanine hydroxylase, leading to accumulation of phenylalanine.",
    ambiguityType: "precise",
    sourceType: "textbook_fact",
  },
  {
    id: 3,
    question: "What is the most common cause of community-acquired pneumonia in adults?",
    answer: "Streptococcus pneumoniae",
    category: "Microbiology",
    difficulty: "easy",
    explanation: "Streptococcus pneumoniae (pneumococcus) is responsible for the majority of community-acquired pneumonia cases.",
    ambiguityType: "ambiguous",
    sourceType: "clinical_guideline",
  },
  {
    id: 4,
    question: "Which nerve is damaged in carpal tunnel syndrome?",
    answer: "Median nerve",
    category: "Anatomy",
    difficulty: "easy",
    explanation: "Carpal tunnel syndrome results from compression of the median nerve as it passes through the carpal tunnel.",
    ambiguityType: "precise",
    sourceType: "textbook_fact",
  },
  {
    id: 5,
    question: "What is the mechanism of action of aspirin?",
    answer: "Irreversible inhibition of COX-1 and COX-2 enzymes",
    category: "Pharmacology",
    difficulty: "medium",
    explanation: "Aspirin acetylates and irreversibly inhibits cyclooxygenase enzymes, preventing prostaglandin and thromboxane synthesis.",
    ambiguityType: "precise",
    sourceType: "textbook_fact",
  },
  {
    id: 6,
    question: "Which vitamin deficiency causes scurvy?",
    answer: "Vitamin C (ascorbic acid)",
    category: "Nutrition",
    difficulty: "easy",
    explanation: "Scurvy results from vitamin C deficiency, impeding collagen synthesis and causing bleeding gums and poor wound healing.",
    ambiguityType: "precise",
    sourceType: "textbook_fact",
  },
  {
    id: 7,
    question: "What is the gold standard test for diagnosing pulmonary embolism?",
    answer: "CT pulmonary angiography (CTPA)",
    category: "Radiology",
    difficulty: "medium",
    explanation: "CTPA is the preferred diagnostic test for PE due to its high sensitivity and specificity.",
    ambiguityType: "ambiguous",
    sourceType: "clinical_guideline",
  },
  {
    id: 8,
    question: "Which electrolyte abnormality is most commonly associated with digoxin toxicity?",
    answer: "Hypokalemia",
    category: "Pharmacology",
    difficulty: "hard",
    explanation: "Hypokalemia potentiates digoxin toxicity by increasing its binding to Na+/K+-ATPase.",
    ambiguityType: "ambiguous",
    sourceType: "textbook_fact",
  },
  {
    id: 9,
    question: "What is the most common type of kidney stone?",
    answer: "Calcium oxalate stones",
    category: "Nephrology",
    difficulty: "easy",
    explanation: "Calcium oxalate is responsible for approximately 80% of all kidney stones.",
    ambiguityType: "ambiguous",
    sourceType: "textbook_fact",
  },
  {
    id: 10,
    question: "Which chromosome is affected in Down syndrome?",
    answer: "Chromosome 21 (trisomy 21)",
    category: "Genetics",
    difficulty: "easy",
    explanation: "Down syndrome is caused by trisomy 21, the presence of an extra copy of chromosome 21.",
    ambiguityType: "precise",
    sourceType: "textbook_fact",
  },
  {
    id: 11,
    question: "What is the mechanism of HIV antiviral resistance to nucleoside reverse transcriptase inhibitors?",
    answer: "Mutations in the reverse transcriptase gene that reduce drug binding or enhance excision",
    category: "Microbiology",
    difficulty: "hard",
    explanation: "NRTI resistance occurs via M184V mutation (reduced binding) or thymidine analog mutations (enhanced excision).",
    ambiguityType: "precise",
    sourceType: "textbook_fact",
  },
  {
    id: 12,
    question: "Which cell type is primarily affected in multiple sclerosis?",
    answer: "Oligodendrocytes (myelin-producing cells in the CNS)",
    category: "Neurology",
    difficulty: "medium",
    explanation: "MS involves autoimmune destruction of oligodendrocytes and myelin in the central nervous system.",
    ambiguityType: "precise",
    sourceType: "textbook_fact",
  },
  {
    id: 13,
    question: "What is the normal range of serum sodium?",
    answer: "135–145 mEq/L",
    category: "Clinical Chemistry",
    difficulty: "easy",
    explanation: "Normal serum sodium ranges between 135 and 145 milliequivalents per liter.",
    ambiguityType: "precise",
    sourceType: "textbook_fact",
  },
  {
    id: 14,
    question: "Which artery supplies the sinoatrial node in most individuals?",
    answer: "Right coronary artery",
    category: "Anatomy",
    difficulty: "hard",
    explanation: "In ~60% of people, the SA node is supplied by the right coronary artery; in ~40% by the left circumflex.",
    ambiguityType: "ambiguous",
    sourceType: "textbook_fact",
  },
  {
    id: 15,
    question: "What is the treatment of choice for Clostridioides difficile (C. diff) infection?",
    answer: "Vancomycin (oral) or fidaxomicin",
    category: "Pharmacology",
    difficulty: "medium",
    explanation: "Current guidelines recommend oral vancomycin or fidaxomicin for C. difficile infection.",
    ambiguityType: "ambiguous",
    sourceType: "clinical_guideline",
  },
  {
    id: 16,
    question: "Which hormone is produced by the beta cells of the pancreas?",
    answer: "Insulin",
    category: "Endocrinology",
    difficulty: "easy",
    explanation: "Beta cells of the islets of Langerhans produce insulin, the primary hormone for glucose uptake.",
    ambiguityType: "precise",
    sourceType: "textbook_fact",
  },
  {
    id: 17,
    question: "What is the most sensitive early marker of acute myocardial infarction?",
    answer: "Troponin I or Troponin T",
    category: "Clinical Chemistry",
    difficulty: "medium",
    explanation: "Cardiac troponins are highly sensitive and specific markers, detectable within 3-4 hours of myocardial injury.",
    ambiguityType: "ambiguous",
    sourceType: "clinical_guideline",
  },
  {
    id: 18,
    question: "Which bacteria produces the Shiga toxin?",
    answer: "Escherichia coli O157:H7 and Shigella dysenteriae",
    category: "Microbiology",
    difficulty: "medium",
    explanation: "Shiga toxin is produced by Shigella dysenteriae type 1 and enterohemorrhagic E. coli strains like O157:H7.",
    ambiguityType: "precise",
    sourceType: "textbook_fact",
  },
  {
    id: 19,
    question: "What is the pathophysiology of myasthenia gravis?",
    answer: "Autoantibodies against acetylcholine receptors at the neuromuscular junction",
    category: "Neurology",
    difficulty: "hard",
    explanation: "Myasthenia gravis is caused by IgG antibodies against nicotinic acetylcholine receptors, reducing neuromuscular transmission.",
    ambiguityType: "precise",
    sourceType: "textbook_fact",
  },
  {
    id: 20,
    question: "What is the primary function of the lymphatic system?",
    answer: "Fluid homeostasis, immune surveillance, and lipid absorption from the gut",
    category: "Physiology",
    difficulty: "medium",
    explanation: "The lymphatic system returns interstitial fluid to circulation, supports immune function, and transports dietary lipids.",
    ambiguityType: "precise",
    sourceType: "textbook_fact",
  },
  {
    id: 21,
    question: "Which type of necrosis is characteristic of ischemic injury in the brain?",
    answer: "Liquefactive necrosis",
    category: "Pathology",
    difficulty: "medium",
    explanation: "The brain undergoes liquefactive necrosis after ischemic injury due to its high lipid content and lack of structural framework.",
    ambiguityType: "precise",
    sourceType: "textbook_fact",
  },
  {
    id: 22,
    question: "What is the most common benign tumor of the uterus?",
    answer: "Leiomyoma (fibroid)",
    category: "Pathology",
    difficulty: "easy",
    explanation: "Leiomyomas, or fibroids, are the most common benign neoplasms of the uterus, arising from smooth muscle.",
    ambiguityType: "ambiguous",
    sourceType: "textbook_fact",
  },
  {
    id: 23,
    question: "Which immunoglobulin class is primarily responsible for the immediate hypersensitivity reaction in asthma?",
    answer: "IgE",
    category: "Immunology",
    difficulty: "easy",
    explanation: "IgE binds to mast cells and basophils, mediating type I hypersensitivity reactions seen in asthma and allergies.",
    ambiguityType: "precise",
    sourceType: "textbook_fact",
  },
  {
    id: 24,
    question: "Which cytokine is the primary driver of fever during the acute phase response?",
    answer: "Interleukin-1 (IL-1)",
    category: "Immunology",
    difficulty: "medium",
    explanation: "IL-1, along with IL-6 and TNF-alpha, acts on the hypothalamus to raise the thermoregulatory set point and induce fever.",
    ambiguityType: "ambiguous",
    sourceType: "textbook_fact",
  },
  {
    id: 25,
    question: "A patient presents with autoimmune destruction of pancreatic alpha cells, leading to insulin-dependent diabetes. Which cells are actually destroyed in type 1 diabetes?",
    answer: "Beta cells",
    category: "Endocrinology",
    difficulty: "medium",
    explanation: "Type 1 diabetes results from autoimmune destruction of insulin-producing beta cells, not alpha cells, which produce glucagon.",
    ambiguityType: "precise",
    sourceType: "constructed",
  },
  {
    id: 26,
    question: "Which class of immunoglobulin is the most abundant in serum?",
    answer: "IgG",
    category: "Immunology",
    difficulty: "easy",
    explanation: "IgG constitutes approximately 75-80% of total serum immunoglobulins.",
    ambiguityType: "precise",
    sourceType: "textbook_fact",
  },
  {
    id: 27,
    question: "What type of hypersensitivity reaction is involved in rheumatoid arthritis, driven primarily by antigen-antibody immune complex deposition?",
    answer: "Type III hypersensitivity",
    category: "Immunology",
    difficulty: "hard",
    explanation: "Rheumatoid arthritis involves type III hypersensitivity through immune complex deposition in joints, alongside type IV cell-mediated components.",
    ambiguityType: "ambiguous",
    sourceType: "clinical_guideline",
  },
  {
    id: 28,
    question: "A clinician orders a beta-blocker, propranolol, to treat a patient's pheochromocytoma-induced hypertension before surgery. Which class of drug should actually be given first in pheochromocytoma management?",
    answer: "Alpha-blockers (e.g., phenoxybenzamine)",
    category: "Pharmacology",
    difficulty: "hard",
    explanation: "Alpha-blockade must precede beta-blockade in pheochromocytoma to prevent unopposed alpha-adrenergic stimulation and hypertensive crisis.",
    ambiguityType: "precise",
    sourceType: "constructed",
  },
  {
    id: 29,
    question: "What is the characteristic histological finding in Hodgkin lymphoma?",
    answer: "Reed-Sternberg cells",
    category: "Pathology",
    difficulty: "medium",
    explanation: "Reed-Sternberg cells, large binucleate cells with prominent nucleoli, are the diagnostic hallmark of Hodgkin lymphoma.",
    ambiguityType: "precise",
    sourceType: "textbook_fact",
  },
  {
    id: 30,
    question: "What is the gold standard imaging modality for diagnosing acute appendicitis in adults?",
    answer: "CT scan of the abdomen and pelvis",
    category: "Radiology",
    difficulty: "medium",
    explanation: "CT is generally considered the gold standard for appendicitis in adults, though ultrasound is preferred in children and pregnant patients.",
    ambiguityType: "ambiguous",
    sourceType: "clinical_guideline",
  },
  {
    id: 31,
    question: "A patient with suspected Graves' disease is found to have elevated TSH along with elevated free T4. Which TSH finding would actually be expected in Graves' disease?",
    answer: "Low (suppressed) TSH",
    category: "Endocrinology",
    difficulty: "medium",
    explanation: "Graves' disease causes primary hyperthyroidism, which suppresses TSH via negative feedback, not elevated TSH.",
    ambiguityType: "precise",
    sourceType: "constructed",
  },
  {
    id: 32,
    question: "Which type of collagen is predominantly found in skin and bone?",
    answer: "Type I collagen",
    category: "Biochemistry",
    difficulty: "medium",
    explanation: "Type I collagen is the most abundant collagen type in the body, forming the major structural component of skin, bone, and tendons.",
    ambiguityType: "precise",
    sourceType: "textbook_fact",
  },
  {
    id: 33,
    question: "What is the best initial treatment for an anaphylactic reaction?",
    answer: "Intramuscular epinephrine",
    category: "Pharmacology",
    difficulty: "easy",
    explanation: "Epinephrine given intramuscularly is the first-line treatment for anaphylaxis, reversing bronchospasm, hypotension, and edema.",
    ambiguityType: "ambiguous",
    sourceType: "clinical_guideline",
  },
  {
    id: 34,
    question: "Which part of the nephron is the primary site of action of loop diuretics such as furosemide?",
    answer: "Thick ascending limb of the loop of Henle",
    category: "Pharmacology",
    difficulty: "medium",
    explanation: "Loop diuretics inhibit the Na-K-2Cl cotransporter in the thick ascending limb of the loop of Henle.",
    ambiguityType: "precise",
    sourceType: "textbook_fact",
  },
  {
    id: 35,
    question: "A patient with B12 deficiency is treated, but the physician notes the deficiency is due to lack of intrinsic factor produced by gastric chief cells. Which gastric cells actually produce intrinsic factor?",
    answer: "Parietal cells",
    category: "Physiology",
    difficulty: "medium",
    explanation: "Intrinsic factor is secreted by gastric parietal cells, not chief cells, which secrete pepsinogen.",
    ambiguityType: "precise",
    sourceType: "constructed",
  },
  {
    id: 36,
    question: "What is the characteristic pattern of inheritance for hemophilia A?",
    answer: "X-linked recessive",
    category: "Genetics",
    difficulty: "easy",
    explanation: "Hemophilia A results from a deficiency of factor VIII and follows an X-linked recessive inheritance pattern.",
    ambiguityType: "precise",
    sourceType: "textbook_fact",
  },
  {
    id: 37,
    question: "Which type of necrosis is classically seen in tuberculosis granulomas?",
    answer: "Caseous necrosis",
    category: "Pathology",
    difficulty: "medium",
    explanation: "Caseous necrosis, with a cheese-like friable appearance, is characteristic of granulomas in tuberculosis.",
    ambiguityType: "precise",
    sourceType: "textbook_fact",
  },
  {
    id: 38,
    question: "What is the first-line imaging study for evaluating suspected stroke within the first few hours of symptom onset?",
    answer: "Non-contrast CT scan of the head",
    category: "Radiology",
    difficulty: "easy",
    explanation: "Non-contrast head CT is the initial imaging study of choice to rapidly distinguish ischemic from hemorrhagic stroke.",
    ambiguityType: "ambiguous",
    sourceType: "clinical_guideline",
  },
  {
    id: 39,
    question: "A patient with chronic granulomatous disease has defective neutrophils due to a deficiency of myeloperoxidase, leading to recurrent infections. Which enzyme deficiency actually causes chronic granulomatous disease?",
    answer: "NADPH oxidase",
    category: "Immunology",
    difficulty: "hard",
    explanation: "Chronic granulomatous disease results from a defect in NADPH oxidase, impairing the respiratory burst, not a myeloperoxidase deficiency.",
    ambiguityType: "ambiguous",
    sourceType: "constructed",
  },
  {
    id: 40,
    question: "What is the classic triad of symptoms in Wernicke encephalopathy?",
    answer: "Confusion, ataxia, and ophthalmoplegia",
    category: "Neurology",
    difficulty: "hard",
    explanation: "Wernicke encephalopathy, caused by thiamine deficiency, classically presents with the triad of confusion, ataxia, and ophthalmoplegia.",
    ambiguityType: "precise",
    sourceType: "textbook_fact",
  },
];

export const categories = [...new Set(medicalDataset.map((q) => q.category))];
export const difficulties = ["easy", "medium", "hard"] as const;
export const sourceTypes = ["textbook_fact", "clinical_guideline", "constructed"] as const;

export interface ExperimentResult {
  questionId: number;
  question: string;
  groundTruth: string;
  modelResponse: string;
  isCorrect: boolean;
  isHallucination: boolean;
  hallucinationType?: "factual_error" | "fabricated" | "overconfident";
  model: string;
  promptStrategy: string;
  confidence?: number;
  ambiguityType?: "precise" | "ambiguous";
  semanticCorrect?: boolean;
  judgeConfidence?: number;
  judgeRationale?: string;
}

export interface ExperimentConfig {
  model: string;
  promptStrategy: string;
  sampleCount: number;
  customPrompt?: string;
}